<!-- index.php -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>My PHP Page</title>
</head>
<body>
  <h1>Hello from PHP + HTML!</h1>

  <?php
    echo "<p>This paragraph is generated by PHP.</p>";
  ?>

  <p>This paragraph is pure HTML.</p>
</body>
</html>